### ISSUE TITLE
A suggestion

### ISSUE THREAD

**Issue by BankofFunny** [a2800276/hexy.js#10]
Offset:  03020100  07060504  0B0A0908  0C0D0E0F
00000000:  20000868  000000C1  000000C9  00000a59
....

addresses in a group sort of descending order.
readable for human in case that a group is a 32 bit integer data

**Comment by a2800276** [comment]
Hi Bank, sorry about taking so long getting back to you. I'm afraid I don't understand what you are suggesting. Something to do with byte order?
