### ISSUE TITLE
Split table...

### ISSUE THREAD

**Issue by antonedvard** [a2800276/hexy.js#12]
First off let me say that i love hexy! Really a neat tool to pretty print those hex demons...

This is more of a "request" than an issue...

Would it be possible to split the hex table and the ascii table ? so that you could get them in like 2 separate strings or only print the ascii table or only the hex table... i know that its possible to remove ascii from annotation but would it be possible to split them? :)

Best regards! Thanks for a great tool :)

**Comment by a2800276** [comment]
Hi Anton, thanks :)

I'm not sure what the interface could look like... Can you explain the use case? I guess it would be possible to add a "ascii_only" format.annotate option. You'd need to run hexy twice, but would that accomplish what you're aiming for? Two passes may not be ideal, but hex formatting is typically not really performance critical :)

**Comment by a2800276** [comment]
Still not sure why you need to split the hex and ascii though... Did you want to submit a patch?

**Comment by antonedvard** [comment]
Im piping the table to browser from a server and in browser im parsing the hex table and wrapping it in some html blocks to make interactive, thought it would prob be easier to send 2 strings instead of trying to split the ascii table from the hex table in browser..

might submit it, haven't looked at the source code, will check it out when i get the free time ;P

**Comment by a2800276** [comment]
Two suggestions that may be more expediant:

- you can run the lib in the browser
- hexy can generate html directly if you set the `html` property of the format options

**Comment by windhamwong** [comment]
Hello, I have done a PR that allows you to use TAB for separating the Hex Data and ASCII Data. This should allow you to do regex or split with TAB to get 2 separated contents of hexdump.
